# Rails Template - Reverse Engineered
# Generated by git-template reverse_engineer command
# Source: examples/rails8-simple
# Generated at: 2025-12-20 13:07:01

# GitTemplate::Generators::Routes (1 file(s))

# Create config/routes.rb
create_file 'config/routes.rb' do <<-RUBY
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
end
RUBY
end
